#doit.sh

#cleanup
rm -rf obj_dir
rm -f counter.vcd

#run Verilator to translate Verilog into C++, includeing C++ testbench 
verilator -Wall --cc --trace counter.sv --exe count_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcounter.mk Vcounter

#run executable simulation file
obj_dir/Vcounter

#type "./doit.sh" to run the script